### ISSUE TITLE
:sparkles: Enrich tasks documentation

### ISSUE THREAD

**Issue by nbrouand** [chutney-testing/chutney-testing.github.io#26]
Take inspiration from the documentation already written for the action [HTTP](https://github.com/chutney-testing/chutney-testing.github.io/blob/main/docs/actions/http.md)
Feel free to write all or part of the actions in each sections.
NB: task == action but we dont have merged the [PR](https://github.com/chutney-testing/chutney/pull/844) yet

- [ ] [AMQP](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/amqp) (9 actions) Need to be review in depth (finally action,...)
- [x] [Assertions](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/assertion) (7 actions)
- [ ]  [Groovy](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/groovy) (1 action)
- [x] [Jms](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/jms) (5 actions)
- [ ] [Kafka](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/kafka) (4 actions)
- [ ] [Micrometer](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/micrometer) (6 actions)
- [x] [Mongo](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/mongo) (6 actions)
- [x] [Radius](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/radius) (2 actions)
- [ ] [Selenium](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/selenium) (16 actions)
- [x] [Sql](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/sql) (1 action)
- [x] [Ssh](https://github.com/chutney-testing/chutney/tree/master/task-impl/src/main/java/com/chutneytesting/task/ssh) (9 actions)

## Others tasks
- [ ] Add link to the code in each action

**Comment by bessonm** [comment]
I am taking over the SQL action since it looks easy but has much more to document than it looks

**Comment by nbrouand** [comment]
splitted issues
