### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nbrouand** [chutney-testing/chutney-testing.github.io#9]
### Overview 

- I find there is too much text.  It should be better to have less text, more links to others pages. Just keep text until the getting started link. The others sections in an other pages. :white_check_mark:
- I would like to add an image like the one which compare Chutney to others tests tools in section "Why another test tool" :white_check_mark:

### Getting started
- ~~graddle => gradle~~
- minimal setup section : i will add two links to two example projects for maven (https://github.com/chutney-testing/chutney-kotlin-dsl/blob/master/example/pom.xml) and kotlin (https://github.com/chutney-testing/chutney-kotlin-dsl/blob/master/example/build.gradle.kts)  :white_check_mark:
- kotlin section => Specific to kotlin, not to Chutney => make a note to gain space :white_check_mark:
- The page is too long, i will split the page like that : :white_check_mark:
  - Introduction + Minimal setup
  - Write your first scenario
  - Run your scenario

### Write your first scenario

- "Here we use the Chutney Kotlin DSL to declare a target." => redundant, remove  :white_check_mark:
- "Here we use the Chutney Kotlin DSL to declare an environment." => redundant, remove  :white_check_mark:
- "As you can see," => too much , to remove As you can see, :white_check_mark:
-  i dont like the name of the variable "www". I prefer to have something like myTestingEnvironment
- "Here we use the Chutney Kotlin DSL to declare a Scenario."' => redundant, remove  :white_check_mark:
- "As you can see" => remove :white_check_mark:

### Run your scenario

- I prefer to begin with the junit way than the launcher wau :white_check_mark:
- "As you can see, this is a simple JUnit test."=> remove :white_check_mark:
- "Configure your build tool" => collapsable to take less space  :white_check_mark:
- add a link to our example : 
  - https://github.com/chutney-testing/chutney-kotlin-dsl/blob/master/example/src/test/kotlin/com/chutneytesting/ChutneyEngineTest.kt
  - https://github.com/chutney-testing/chutney-kotlin-dsl/blob/master/example/src/test/kotlin/com/chutneytesting/DefaultWrappingTest.kt

- "The JUnit5 engine does not take environment definition from Kotlin but instead from JSON files." => false ? To be verified :boom:

**Comment by bessonm** [comment]
I close the issue since all points were addressed
